repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: bash -c 'cd backend && export POETRY_CONFIG_DIR=$(pwd)/../.poetry_config && export POETRY_CACHE_DIR=$(pwd)/../.poetry_cache && export POETRY_VIRTUALENVS_IN_PROJECT=true && ../.venv/bin/poetry run flake8 "${@#backend/}"' --
        language: system
        types: [python]
        files: ^backend/
    -   id: pylint
        name: pylint
        entry: bash -c 'cd backend && export POETRY_CONFIG_DIR=$(pwd)/../.poetry_config && export POETRY_CACHE_DIR=$(pwd)/../.poetry_cache && export POETRY_VIRTUALENVS_IN_PROJECT=true && export PYLINTHOME=$(pwd)/../.pylint.d && ../.venv/bin/poetry run pylint "${@#backend/}"' --
        language: system
        types: [python]
        files: ^backend/
    -   id: mypy
        name: mypy
        entry: bash -c 'cd backend && export POETRY_CONFIG_DIR=$(pwd)/../.poetry_config && export POETRY_CACHE_DIR=$(pwd)/../.poetry_cache && export POETRY_VIRTUALENVS_IN_PROJECT=true && export MYPY_CACHE_DIR=$(pwd)/../.mypy_cache && ../.venv/bin/poetry run mypy "${@#backend/}"' --
        language: system
        types: [python]
        files: ^backend/
    -   id: pytest
        name: pytest
        entry: bash -c 'cd backend && export POETRY_CONFIG_DIR=$(pwd)/../.poetry_config && export POETRY_CACHE_DIR=$(pwd)/../.poetry_cache && export POETRY_VIRTUALENVS_IN_PROJECT=true && ../.venv/bin/poetry run pytest'
        language: system
        types: [python]
        files: ^backend/
        pass_filenames: false