default_stages: [pre-commit]

repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        <<: &poetry_run
            language: system
            types: [python]
            files: ^backend/
            entry: bash -c 'cd backend && export POETRY_CONFIG_DIR=$(pwd)/../.cache/poetry/config && export POETRY_CACHE_DIR=$(pwd)/../.cache/poetry/cache && export POETRY_VIRTUALENVS_IN_PROJECT=true && export PYLINTHOME=$(pwd)/../.cache/pylint.d && export MYPY_CACHE_DIR=$(pwd)/../.cache/mypy/cache && tool=$1; shift; ../.venv/bin/poetry run $tool "${@#backend/}"' --
        args: [flake8]
    -   id: pylint
        name: pylint
        <<: *poetry_run
        args: [pylint]
    -   id: mypy
        name: mypy
        <<: *poetry_run
        args: [mypy]
    -   id: pytest
        name: pytest
        <<: *poetry_run
        args: [pytest]
        pass_filenames: false
    -   id: generate-openapi-schema
        name: Generate backend OpenAPI schema
        <<: *poetry_run
        args: [python, regen_schema.py]
        pass_filenames: false
    -   id: frontend-format
        name: frontend format
        <<: &npm_run
            language: system
            files: ^frontend/
            entry: bash -c 'cd frontend && command=$1; shift; npm run $command' --
            pass_filenames: false
        args: [format]
    -   id: frontend-lint
        name: frontend lint
        <<: *npm_run
        args: [lint]
    -   id: frontend-type-check
        name: frontend type-check
        <<: *npm_run
        args: [type-check]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-case-conflict
-   repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
    -   id: isort
        name: isort (python)
